### ISSUE TITLE
Valid (Dutch not international) vaccination certificate given after only one vaccination of Pfizer

### ISSUE THREAD

**Issue by Yoeori** [minvws/nl-covid19-coronacheck-app-android#28] opened 2021-06-25 11:19 UTC
### Describe the bug, issue or concern
Yesterday I finally got the chance to receive my first vaccination with Pfizer and of course after I got home I tinkered with the app (see steps in To reproduce). While I ended the night with a valid certificate because I've recently been negatively tested (valid until 5:00 AM this morning), I woke up to find a valid vaccination certificate, which I was successfully able to use in the scanner app.

I've checked at mijn.rivm.nl to see if my vaccination was correctly registered, and no problems seem to have occurred there.

### To Reproduce
1. Get vaccinated (Pfizer) :100: 
2. Load vaccination certificate into the Coronamelder app (around 5 hours after vaccination)
3. Get greeted by a message that my vaccination is only valid internationally and not yet in the Netherlands
3. Load negative test result gotten from the GGD (around 35 hours old at this point)
4. Get a valid negative test result QR-code
5. (next morning) See that my negative test result has correctly disappeared from the Netherlands part and is still visible in the international tab
6. Find a valid vaccination QR-code in the Netherlands portion
7. Scan the QR-code in the scanner app and get greeted by a green checkmark.

### Expected behavior
Since I've only had one shot of Pfizer I expect my vaccination to not be valid yet in the Netherlands.

### Screenshots
Unable to take screenshots.

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android 10 (Oxygen OS 10.0.1)
 - Browser: Chrome
 - Version : 91.0.4472.120

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md
~(I'll have to read these later sorry, as I'm late for some other things)~

**Comment by WoutervdBrink** [comment] 2021-06-29 06:37
I have reproduced this issue: first I fetched my vaccination details. The app correctly said that one vaccination is not enough. Then I entered a negative test result, which produced a valid QR. This night the test result became invalid and now I have a valid QR for my vaccination, which I just confirmed with the scanner. I still have not yet had my second vaccination and I have never had covid (or at least, I've never been tested positive).

**Comment by Yoeori** [comment] 2021-06-29 12:04
According to this: https://www.nu.nl/tech/6142204/duizenden-mensen-kregen-na-een-prik-onterecht-vaccinatiebewijs-in-app.html it seems to be a known bug which is in the process of being resolved? If it has indeed been fixed, this issue can be closed. However, it's a bit annoying that no reaction has been given whatsoever.

**Comment by BartNijland91** [comment] 2021-06-30 12:13
@Yoeori this was indeed a backend issue that has been fixed in a new release. Communication is a bit slow due to releases/hotfixes.

**Closed by BartNijland91** 2021-06-30 12:13 UTC
